# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dev/Documents/Elliot/MySpikingNetworks

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dev/Documents/Elliot/MySpikingNetworks

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dev/Documents/Elliot/MySpikingNetworks/CMakeFiles /home/dev/Documents/Elliot/MySpikingNetworks/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dev/Documents/Elliot/MySpikingNetworks/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SimpleExample

# Build rule for target.
SimpleExample: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SimpleExample
.PHONY : SimpleExample

# fast build rule for target.
SimpleExample/fast:
	$(MAKE) -f CMakeFiles/SimpleExample.dir/build.make CMakeFiles/SimpleExample.dir/build
.PHONY : SimpleExample/fast

#=============================================================================
# Target rules for targets named BaseExperiment

# Build rule for target.
BaseExperiment: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BaseExperiment
.PHONY : BaseExperiment

# fast build rule for target.
BaseExperiment/fast:
	$(MAKE) -f CMakeFiles/BaseExperiment.dir/build.make CMakeFiles/BaseExperiment.dir/build
.PHONY : BaseExperiment/fast

#=============================================================================
# Target rules for targets named SimpleNetwork

# Build rule for target.
SimpleNetwork: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SimpleNetwork
.PHONY : SimpleNetwork

# fast build rule for target.
SimpleNetwork/fast:
	$(MAKE) -f CMakeFiles/SimpleNetwork.dir/build.make CMakeFiles/SimpleNetwork.dir/build
.PHONY : SimpleNetwork/fast

#=============================================================================
# Target rules for targets named PropagationExperiment

# Build rule for target.
PropagationExperiment: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PropagationExperiment
.PHONY : PropagationExperiment

# fast build rule for target.
PropagationExperiment/fast:
	$(MAKE) -f CMakeFiles/PropagationExperiment.dir/build.make CMakeFiles/PropagationExperiment.dir/build
.PHONY : PropagationExperiment/fast

#=============================================================================
# Target rules for targets named SpikeDummy

# Build rule for target.
SpikeDummy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SpikeDummy
.PHONY : SpikeDummy

# fast build rule for target.
SpikeDummy/fast:
	$(MAKE) -f Spike/Build/Spike/CMakeFiles/SpikeDummy.dir/build.make Spike/Build/Spike/CMakeFiles/SpikeDummy.dir/build
.PHONY : SpikeDummy/fast

#=============================================================================
# Target rules for targets named Spike

# Build rule for target.
Spike: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Spike
.PHONY : Spike

# fast build rule for target.
Spike/fast:
	$(MAKE) -f Spike/Build/Spike/CMakeFiles/Spike.dir/build.make Spike/Build/Spike/CMakeFiles/Spike.dir/build
.PHONY : Spike/fast

#=============================================================================
# Target rules for targets named SpikeCUDA

# Build rule for target.
SpikeCUDA: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SpikeCUDA
.PHONY : SpikeCUDA

# fast build rule for target.
SpikeCUDA/fast:
	$(MAKE) -f Spike/Build/Spike/CMakeFiles/SpikeCUDA.dir/build.make Spike/Build/Spike/CMakeFiles/SpikeCUDA.dir/build
.PHONY : SpikeCUDA/fast

BaseExperiment.o: BaseExperiment.cpp.o

.PHONY : BaseExperiment.o

# target to build an object file
BaseExperiment.cpp.o:
	$(MAKE) -f CMakeFiles/BaseExperiment.dir/build.make CMakeFiles/BaseExperiment.dir/BaseExperiment.cpp.o
.PHONY : BaseExperiment.cpp.o

BaseExperiment.i: BaseExperiment.cpp.i

.PHONY : BaseExperiment.i

# target to preprocess a source file
BaseExperiment.cpp.i:
	$(MAKE) -f CMakeFiles/BaseExperiment.dir/build.make CMakeFiles/BaseExperiment.dir/BaseExperiment.cpp.i
.PHONY : BaseExperiment.cpp.i

BaseExperiment.s: BaseExperiment.cpp.s

.PHONY : BaseExperiment.s

# target to generate assembly for a file
BaseExperiment.cpp.s:
	$(MAKE) -f CMakeFiles/BaseExperiment.dir/build.make CMakeFiles/BaseExperiment.dir/BaseExperiment.cpp.s
.PHONY : BaseExperiment.cpp.s

PropagationExperiment.o: PropagationExperiment.cpp.o

.PHONY : PropagationExperiment.o

# target to build an object file
PropagationExperiment.cpp.o:
	$(MAKE) -f CMakeFiles/PropagationExperiment.dir/build.make CMakeFiles/PropagationExperiment.dir/PropagationExperiment.cpp.o
.PHONY : PropagationExperiment.cpp.o

PropagationExperiment.i: PropagationExperiment.cpp.i

.PHONY : PropagationExperiment.i

# target to preprocess a source file
PropagationExperiment.cpp.i:
	$(MAKE) -f CMakeFiles/PropagationExperiment.dir/build.make CMakeFiles/PropagationExperiment.dir/PropagationExperiment.cpp.i
.PHONY : PropagationExperiment.cpp.i

PropagationExperiment.s: PropagationExperiment.cpp.s

.PHONY : PropagationExperiment.s

# target to generate assembly for a file
PropagationExperiment.cpp.s:
	$(MAKE) -f CMakeFiles/PropagationExperiment.dir/build.make CMakeFiles/PropagationExperiment.dir/PropagationExperiment.cpp.s
.PHONY : PropagationExperiment.cpp.s

SimpleExample.o: SimpleExample.cpp.o

.PHONY : SimpleExample.o

# target to build an object file
SimpleExample.cpp.o:
	$(MAKE) -f CMakeFiles/SimpleExample.dir/build.make CMakeFiles/SimpleExample.dir/SimpleExample.cpp.o
.PHONY : SimpleExample.cpp.o

SimpleExample.i: SimpleExample.cpp.i

.PHONY : SimpleExample.i

# target to preprocess a source file
SimpleExample.cpp.i:
	$(MAKE) -f CMakeFiles/SimpleExample.dir/build.make CMakeFiles/SimpleExample.dir/SimpleExample.cpp.i
.PHONY : SimpleExample.cpp.i

SimpleExample.s: SimpleExample.cpp.s

.PHONY : SimpleExample.s

# target to generate assembly for a file
SimpleExample.cpp.s:
	$(MAKE) -f CMakeFiles/SimpleExample.dir/build.make CMakeFiles/SimpleExample.dir/SimpleExample.cpp.s
.PHONY : SimpleExample.cpp.s

SimpleNetwork.o: SimpleNetwork.cpp.o

.PHONY : SimpleNetwork.o

# target to build an object file
SimpleNetwork.cpp.o:
	$(MAKE) -f CMakeFiles/SimpleNetwork.dir/build.make CMakeFiles/SimpleNetwork.dir/SimpleNetwork.cpp.o
.PHONY : SimpleNetwork.cpp.o

SimpleNetwork.i: SimpleNetwork.cpp.i

.PHONY : SimpleNetwork.i

# target to preprocess a source file
SimpleNetwork.cpp.i:
	$(MAKE) -f CMakeFiles/SimpleNetwork.dir/build.make CMakeFiles/SimpleNetwork.dir/SimpleNetwork.cpp.i
.PHONY : SimpleNetwork.cpp.i

SimpleNetwork.s: SimpleNetwork.cpp.s

.PHONY : SimpleNetwork.s

# target to generate assembly for a file
SimpleNetwork.cpp.s:
	$(MAKE) -f CMakeFiles/SimpleNetwork.dir/build.make CMakeFiles/SimpleNetwork.dir/SimpleNetwork.cpp.s
.PHONY : SimpleNetwork.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SimpleExample"
	@echo "... BaseExperiment"
	@echo "... SimpleNetwork"
	@echo "... PropagationExperiment"
	@echo "... SpikeDummy"
	@echo "... Spike"
	@echo "... SpikeCUDA"
	@echo "... BaseExperiment.o"
	@echo "... BaseExperiment.i"
	@echo "... BaseExperiment.s"
	@echo "... PropagationExperiment.o"
	@echo "... PropagationExperiment.i"
	@echo "... PropagationExperiment.s"
	@echo "... SimpleExample.o"
	@echo "... SimpleExample.i"
	@echo "... SimpleExample.s"
	@echo "... SimpleNetwork.o"
	@echo "... SimpleNetwork.i"
	@echo "... SimpleNetwork.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

